name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*
    - feature/*

stages:
- stage: deployDev
  displayName: Deploy DEV Global - ARM Variant
  jobs:
  - template: templates/deploy.yml
    parameters:
      serviceConnection: $(devServiceConnection)
      subscriptionId: $(devSubscriptionId)
      tenantId: $(tenantId)
      environmentId: 'd01'
      environmentName: 'dev'
  - template: templates/permissions.yml
    parameters:
      dependencyName: deployGlobaldev
      serviceConnection: $(devServiceConnection)
      serviceConnectionApplicationId: $(devServiceConnectionApplicationId)
      environmentId: 'd01'
      environmentName: 'dev'

- stage: deployTest
  displayName: Deploy TEST Global - ARM Variant
  jobs:
  - template: templates/deploy.yml
    parameters:
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      tenantId: $(tenantId)
      environmentId: 't01'
      environmentName: 'test'
  - template: templates/permissions.yml
    parameters:
      dependencyName: deployGlobaltest
      serviceConnection: $(testServiceConnection)
      serviceConnectionApplicationId: $(testServiceConnectionApplicationId)
      environmentId: 't01'
      environmentName: 'test'


- stage: deployInt
  displayName: Deploy INT Global - ARM Variant
  jobs:
  - template: templates/deploy.yml
    parameters:
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      tenantId: $(tenantId)
      environmentId: 't03'
      environmentName: 'int'
  - template: templates/permissions.yml
    parameters:
      dependencyName: deployGlobalint
      serviceConnection: $(testServiceConnection)
      serviceConnectionApplicationId: $(testServiceConnectionApplicationId)
      environmentId: 't03'
      environmentName: 'int'

- stage: deployPp
  displayName: Deploy PP Global - ARM Variant
  jobs:
  - template: templates/deploy.yml
    parameters:
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      tenantId: $(tenantId)
      environmentId: 't02'
      environmentName: 'pp'
  - template: templates/permissions.yml
    parameters:
      dependencyName: deployGlobalpp
      serviceConnection: $(testServiceConnection)
      serviceConnectionApplicationId: $(testServiceConnectionApplicationId)
      environmentId: 't02'
      environmentName: 'pp'

- stage: deployPr
  displayName: Deploy PR Global - ARM Variant
  jobs:
  - template: templates/deploy.yml
    parameters:
      serviceConnection: $(prodServiceConnection)
      subscriptionId: $(prodSubscriptionId)
      tenantId: $(tenantId)
      environmentId: 'p01'
      environmentName: 'pr'
  - template: templates/permissions.yml
    parameters:
      dependencyName: deployGlobalpr
      serviceConnection: $(prodServiceConnection)
      serviceConnectionApplicationId: $(prodServiceConnectionApplicationId)
      environmentId: 'p01'
      environmentName: 'pr'


    