name: $(BuildDefinitionName)_tag-$(BuildID)_at-$(Date:yyyyMMdd)$(Rev:.r)
resources:
  repositories:
    - repository: devopsTemplates
      type: github
      endpoint: DfE-Digital
      name: DFE-Digital/operations-devops-pipeline-templates

trigger:
  branches:
    include:
    - master
    exclude:
    - develop/*
    - feature/*

stages:
- stage: deployDev
  displayName: Deploy DEV Global - ARM Variant
  jobs:
  - template: templates/deploy.yml
    parameters:
      serviceConnection: $(devServiceConnection)
      subscriptionId: $(devSubscriptionId)
      tenantId: $(tenantId)
      environmentId: 'd01'
      environmentName: 'dev'
  - template: templates/permissions.yml
    parameters:
      dependencyName: deploy_dev
      serviceConnection: $(devServiceConnection)
      serviceConnectionObjectId: $(devServiceConnectionObjectId)
      environmentId: 'd01'
      environmentName: 'dev'

- stage: deployTest
  displayName: Deploy TEST Global - ARM Variant
  jobs:
  - template: templates/deploy.yml
    parameters:
      serviceConnection: $(testServiceConnection)
      subscriptionId: $(testSubscriptionId)
      tenantId: $(tenantId)
      environmentId: 't01'
      environmentName: 'test'
  - template: templates/permissions.yml
    parameters:
      dependencyName: deploy_test
      serviceConnection: $(testServiceConnection)
      serviceConnectionObjectId: $(testServiceConnectionObjectId)
      environmentId: 't01'
      environmentName: 'test'
  

    