parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: tenantId
  type: string
- name: environmentId
  type: string
- name: environmentName
  type: string
- name: projectIdentifier
  type: string
  default: 's141'
- name: deploymentLocation
  type: string
  default: westeurope
- name: platformVariableGroupName
  type: string
- name: templatesBaseUri
  type: string
  default: 'https://raw.githubusercontent.com/DFE-Digital/login.dfe.infrastructure/master/'

jobs:
- deployment: deployGlobal${{parameters.environmentName}}
  displayName: Deploy From Templates
  environment: '${{parameters.environmentName}}'
  pool:
    vmImage: ubuntu-latest
  variables:
    group: ${{parameters.platformVariableGroupName}}
    resourceGroupName: ${{parameters.projectIdentifier}}${{parameters.environmentId}}-$(globalName)-$(globalSuffix)
    globalName: signin
    globalSuffix: global
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: $(resourceGroupName)
            tags: $(Tags)
            location: ${{parameters.deploymentLocation}}
            templateFilePath: $(Build.SourcesDirectory)/arm/storage.json
            armParameterOverrideString: '-templatesBaseUri "$(templatesBaseUri)" -skuName "Standard_LRS" -environmentId "${{parameters.environmentId}}" -environmentName "${{parameters.environmentName}}"'
            processOutputs: false
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: $(resourceGroupName)
            location: ${{parameters.deploymentLocation}}
            tags: $(Tags)
            templateFilePath: $(Build.SourcesDirectory)/arm/keyvault.json
            armParameterOverrideString: ' -environmentId "${{parameters.environmentId}}" -tenantId "${{parameters.tenantId}}" -skuName "Standard"'
            processOutputs: false
