parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: tenantId
  type: string
- name: environmentId
  type: string
- name: environmentName
  type: string
- name: projectIdentifier
  type: string
  default: 's141'
- name: deploymentLocation
  type: string
  default: westeurope

jobs:
- deployment: deployGlobal${{parameters.environmentName}}
  displayName: Deploy From Templates
  environment: '${{parameters.environmentName}}'
  pool:
    vmImage: ubuntu-latest
  variables:
    resourceGroupName: ${{parameters.projectIdentifier}}${{parameters.environmentId}}-$(globalName)-$(globalSuffix)
    globalName: signin
    globalSuffix: global
  strategy:
    runOnce:
      deploy:
        steps:
        - checkout: self
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: $(resourceGroupName)
            location: ${{parameters.deploymentLocation}}
            templateFilePath: $(Build.Repository.LocalPath)/login.dfe.global/arm/storage.json
            armParameterOverrideString: ' -skuName "Standard_LRS" -environmentId "${{parameters.environmentId}}"'
            processOutputs: false
        - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
          parameters:
            serviceConnection: ${{parameters.serviceConnection}}
            subscriptionId: ${{parameters.subscriptionId}}
            resourceGroupName: $(resourceGroupName)
            location: ${{parameters.deploymentLocation}}
            templateFilePath: $(Build.Repository.LocalPath)/login.dfe.global/arm/keyvault.json
            armParameterOverrideString: ' -environmentId "${{parameters.environmentId}}" -tenantId "${{parameters.tenantId}}" -skuName "Standard"'
            processOutputs: false
