parameters:
- name: serviceConnection
  type: string
- name: subscriptionId
  type: string
- name: tenantId
  type: string
- name: environmentId
  type: string
- name: environmentName
  type: string
- name: projectIdentifier
  type: string
  default: 's141'
- name: deploymentLocation
  type: string
  default: westeurope

jobs:
- job: deploy_${{parameters.environmentName}}
  displayName: Deploy From Templates
  pool:
    vmImage: ubuntu-latest
  variables:
    resourceGroupName: ${{parameters.projectIdentifier}}${{parameters.environmentId}}-$(globalName)-$(globalSuffix)
    globalName: signin
    globalSuffix: global
  steps:
  - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
    parameters:
      serviceConnection: ${{parameters.serviceConnection}}
      subscriptionId: ${{parameters.subscriptionId}}
      resourceGroupName: $(resourceGroupName)
      location: ${{parameters.deploymentLocation}}
      templateFilePath: $(Build.Repository.LocalPath)/arm/storage.json
      armParameterOverrideString: ' -skuName "Standard_LRS" -environmentId "${{parameters.environmentId}}"'
      processOutputs: false
  - template: /Infrastructure/steps/deploy-template.yml@devopsTemplates
    parameters:
      serviceConnection: ${{parameters.serviceConnection}}
      subscriptionId: ${{parameters.subscriptionId}}
      resourceGroupName: $(resourceGroupName)
      location: ${{parameters.deploymentLocation}}
      templateFilePath: $(Build.Repository.LocalPath)/arm/keyvault.json
      armParameterOverrideString: ' -environmentId "${{parameters.environmentId}}" -tenantId "${{parameters.tenantId}}" -skuName "Standard"'
      processOutputs: false
  # - task: AzureCLI@2
  #   name: postDeploy
  #   displayName: Post Deploy
  #   inputs:
  #     azureSubscription: ${{parameters.serviceConnection}}
  #     scriptType: pscore
  #     scriptLocation: inlineScript
  #     inlineScript: |
  #       $azAccount = az account show | ConvertFrom-Json
  #       write-host $azAccount
  #       write-host Id is : $azAccount.id