parameters:
- name: dependencyName
  type: string
- name: serviceConnection
  type: string
- name: serviceConnectionApplicationId
  type: string
- name: projectIdentifier
  type: string
  default: 's141'
- name: environmentId
  type: string
- name: environmentName
  type: string
- name: platformVariableGroupName
  type: string


jobs:
- job: permissions_${{parameters.environmentName}}
  displayName: Set Post Deploy Permissions
  dependsOn: ${{parameters.dependencyName}}
  pool:
    vmImage: ubuntu-latest
  variables:
  - group: ${{parameters.platformVariableGroupName}}
  - group: platform-global
  - name: resourceGroupName
    value: ${{parameters.projectIdentifier}}${{parameters.environmentId}}-$(globalName)-$(globalSuffix)
  - name: globalName
    value: signin
  - name: globalSuffix
    value: global
  steps:
  - task: AzureCLI@2
    name: postDeploy
    displayName: Add Service Connection SP to KV Access Policy
    inputs:
      azureSubscription: ${{parameters.serviceConnection}}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $kvName = '${{parameters.projectIdentifier}}${{parameters.environmentId}}-signin-global-kv'
        $globalRg = '${{parameters.projectIdentifier}}${{parameters.environmentId}}-signin-global'

        write-host 'getting sp for service connection'

        $spArray = az ad sp list --filter "appId eq '${{parameters.serviceConnectionApplicationId}}'" | ConvertFrom-Json
        $sp = $spArray[0] 

        write-host 'adding kv policy for service connection - application id $($sp.appId)'
        write-host using kv : $kvName in rg : $globalRg
        az keyvault set-policy --name $kvName --spn $sp.appId --certificate-permissions get getissuers list listissuers --secret-permissions get list set
        
        write-host set keyvault policy for MS App Services

        az keyvault set-policy --name $kvName --object-id $(platformGlobalMsAppServicesObjectId) --certificate-permissions get getissuers list listissuers --secret-permissions get list

        write-host set keyvault policy for s141-dfesignin-Managers USR

        az keyvault set-policy --name $kvName --object-id $(platformGlobalSigninOpsManagersGroupObjectId) --key-permissions backup create delete encrypt get import list purge recover restore sign unwrapKey update verify wrapKey --certificate-permissions get list update create import recover backup restore managecontacts manageissuers getissuers listissuers setissuers delete --secret-permissions get list backup delete purge recover restore set --storage-permissions backup delete deletesas get getsas list listsas purge recover regeneratekey restore set setsas update
