parameters:
- name: dependencyName
  type: string
- name: serviceConnection
  type: string
- name: serviceConnectionApplicationId
  type: string
- name: projectIdentifier
  type: string
  default: 's141'
- name: environmentId
  type: string
- name: environmentName
  type: string


jobs:
- job: permissions_${{parameters.environmentName}}
  displayName: Set Post Deploy Permissions
  dependsOn: ${{parameters.dependencyName}}
  pool:
    vmImage: ubuntu-latest
  variables:
    resourceGroupName: ${{parameters.projectIdentifier}}${{parameters.environmentId}}-$(globalName)-$(globalSuffix)
    globalName: signin
    globalSuffix: global
  steps:
  - task: AzureCLI@2
    name: postDeploy
    displayName: Add Service Connection SP to KV Access Policy
    inputs:
      azureSubscription: ${{parameters.serviceConnection}}
      scriptType: pscore
      scriptLocation: inlineScript
      inlineScript: |
        $kvName = '${{parameters.projectIdentifier}}${{parameters.environmentId}}-signin-global-kv'
        $globalRg = '${{parameters.projectIdentifier}}${{parameters.environmentId}}-signin-global'

        write-host 'getting sp for service connection'

        $spArray = az ad sp list --filter "appId eq '${{parameters.serviceConnectionApplicationId}}'" | ConvertFrom-Json
        $sp = $spArray[0] 

        write-host 'adding kv policy for service connection - application id $($sp.appId)'
        write-host using kv : $kvName in rg : $globalRg
        az keyvault set-policy --name $kvName --spn $sp.appId --certificate-permissions get getissuers list listissuers --secret-permissions get list set
        
        write-host set keyvault policy for MS App Services

        az keyvault set-policy --name $kvName --object-id a6621090-e704-45ec-b65f-50257f9d4dcd --certificate-permissions get getissuers list listissuers --secret-permissions get list

        write-host set keyvault policy for s141-dfesignin-Managers USR

        az keyvault set-policy --name $kvName --object-id 4c04a9e6-1ed2-44a6-8db5-ee93b10f79ad --certificate-permissions get list update create import recover backup restore managecontacts manageissuers getissuers listissuers setissuers delete --secret-permissions get list
